export const POST_ADD_PRODUCT_REQ = "POST_ADD_PRODUCT_REQ";
export const POST_ADD_PRODUCT_SUCCESS = "POST_ADD_PRODUCT_SUCCESS";
export const POST_ADD_PRODUCT_REQ_FAILURE = "POST_ADD_PRODUCT_REQ_FAILURE";
